### ISSUE TITLE
Receiving error on response data

### ISSUE THREAD

**Issue by DanielZanchi** [whiteio/LaMa-Eraser-iOS#1]
I keep receiving error on the request.response.

If I print out the data as String:
`"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>400 Bad Request</title>\n<h1>Bad Request</h1>\n<p>The browser (or proxy) sent a request that this server could not understand.</p>\n"`

lama-cleaner is up and running, I am able to use it on 
http://127.0.0.1:8080/

**Comment by whiteio** [comment]
Hey thanks for adding this issue here, I'll try get this working soon. In the meantime you could try using version `0.19.0` of lama-cleaner (https://github.com/Sanster/lama-cleaner/releases/tag/0.19.0) and see if that helps.

**Comment by whiteio** [comment]
README has been updated to include working steps to get it running. https://github.com/whiteio/lama-zits can now be used to run the flask server with the correct version of the lama model.
