### ISSUE TITLE
Could not connect to the server in Mac

### ISSUE THREAD

**Issue by kasarampavan** [whiteio/LaMa-Eraser-iOS#5]
Task <16CC39E2-04EB-489C-8F42-5051188AE9FC>.<1> finished with error [-1004] Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={_kCFStreamErrorCodeKey=61, NSUnderlyingError=0x283d68810 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_NSURLErrorNWPathKey=satisfied (Path is satisfied), viable, interface: lo0, _kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalUploadTask <16CC39E2-04EB-489C-8F42-5051188AE9FC>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalUploadTask <16CC39E2-04EB-489C-8F42-5051188AE9FC>.<1>"
), NSLocalizedDescription=Could not connect to the server., NSErrorFailingURLStringKey=http://127.0.0.1:5000/inpaint, NSErrorFailingURLKey=http://127.0.0.1:5000/inpaint, _kCFStreamErrorDomainKey=1}

Running in physical device only

Flask server is running 

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit

**Comment by whiteio** [comment]
Hey, it'll only work on an iOS simulator. I've updated the README to make this clearer. It won't be able to find the server if the server is just running locally on your computer.
